config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Authentication
  devise_for :users, {}

  # App
  root to: 'home#index'
  resources :properties, only: [:index, :show]

  # Marketing
  namespace :landing_pages do
    resources :franchise, only: [:index, :create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  # Associations
  belongs_to :favoritable, polymorphic: true
  belongs_to :user
end

#------------------------------------------------------------------------------
# Favorite
#
# Name             SQL Type             Null    Primary Default
# ---------------- -------------------- ------- ------- ----------
# id               bigint               false   true
# favoritable_id   integer              true    false
# favoritable_type character varying    true    false
# user_id          bigint               true    false
# created_at       timestamp without time zone false   false
# updated_at       timestamp without time zone false   false
#
#------------------------------------------------------------------------------

app/models/form_objects/contact.rb
# frozen_string_literal: true

class Contact
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :phone, :email, :message

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  validates :name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/franchise_intent.rb
# frozen_string_literal: true

class FranchiseIntent < ApplicationRecord
  # Validations
  validates :first_name, :last_name, :email, :phone,
            :investor_profile, :investment_value, presence: true
end

#------------------------------------------------------------------------------
# FranchiseIntent
#
# Name             SQL Type             Null    Primary Default
# ---------------- -------------------- ------- ------- ----------
# id               bigint               false   true
# first_name       character varying    true    false
# last_name        character varying    true    false
# email            character varying    true    false
# phone            character varying    true    false
# investor_profile integer              true    false
# investment_value integer              true    false
# created_at       timestamp without time zone false   false
# updated_at       timestamp without time zone false   false
#
#------------------------------------------------------------------------------

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  # Associations
  has_many :favorites, as: :favoritable, dependent: :destroy
  belongs_to :user

  # Validations
  validates :cover_image, :name, :amount, :cover_image, presence: true
end

#------------------------------------------------------------------------------
# Property
#
# Name        SQL Type             Null    Primary Default
# ----------- -------------------- ------- ------- ----------
# id          bigint               false   true
# cover_image character varying    true    false
# name        character varying    true    false
# amount      numeric              true    false
# user_id     bigint               true    false
# created_at  timestamp without time zone false   false
# updated_at  timestamp without time zone false   false
#
#------------------------------------------------------------------------------

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Associations
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_many :properties, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

#------------------------------------------------------------------------------
# User
#
# Name                   SQL Type             Null    Primary Default
# ---------------------- -------------------- ------- ------- ----------
# id                     bigint               false   true
# email                  character varying    false   false
# encrypted_password     character varying    false   false
# reset_password_token   character varying    true    false
# reset_password_sent_at timestamp without time zone true    false
# remember_created_at    timestamp without time zone true    false
# created_at             timestamp without time zone false   false
# updated_at             timestamp without time zone false   false
#
#------------------------------------------------------------------------------

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/controllers/landing_pages/franchise_controller.rb
# frozen_string_literal: true

module LandingPages
  class FranchiseController < ApplicationController
    def index
      @franchise_intent = FranchiseIntent.new
    end

    def create
      franchise_intent = FranchiseIntent.new(franchise_intent_params)

      if franchise_intent.save
        flash[:success] = 'Cadastro efetuado com sucesso.'
        redirect_to landing_pages_franchise_index_path
      else
        flash.now[:error] = 'Falha ao efetuar cadastro, tente novamente.'
        render :index
      end
    end

    private

    def franchise_intent_params
      params.require(:franchise_intent)
            .permit(:first_name, :last_name, :email, :phone, :investor_profile, :investor_value)
    end
  end
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  before_action :set_property, only: [:show]

  def index
    @properties = Property.all
  end

  def show
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def load_json_ld(file_name)
    file_path = Rails.root.join('seo', 'ld_json', "#{file_name}.json.erb")

    File.exist?(file_path) ? ld_json_file = File.read(file_path) : return

    content_tag(:script, type: 'application/ld+json') do
      ld_json_file.html_safe
    end
  end
end

app/views/home/index.html.erb
<%= provide :ld_json, 'home' %>

<section id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="bold text-center">Encontre seu lugar<br /> no mundo</h2>
        
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
              <div class="panel-body">
                <%= form_for(:property) do |f| %>
                
                <div class="col-md-9">
                  <%= f.text_field :name, class: 'form-control', required: 'required',
                  placeholder: 'Busque pela região ou empreendimento.', style: 'height: 44px' ;%>
                </div>

                <div class="col-md-3">
                  <%= f.submit 'Buscar', class: 'btn btn-primary btn-lg' %>
                </div>
              <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3 col-md-offset-1">
            <div class="panel panel-default">
              <div class="panel-body">
                <h5 class="bold text-center">
                  Milhares de opções para encontrar
                  o imóvel que combina com você.
                </h5>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="panel panel-default">
              <div class="panel-body">
                <h5 class="bold text-center">
                  Inteligencia Artificial para
                  aumentar exponencialmente as chances de match
                </h5>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="panel panel-default">
              <div class="panel-body">
                <h5 class="bold text-center">
                  Inteligencia de mercado para
                  te ajudar a escolher o melhor negócio
                </h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="simulate">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <h3 class="bold">Calculadora e simulador de<br />
                financiamento imobiliário
                </h3>

                <p>Use nossa calculadora para descobrir como
                aproveitar seu<br /> investimento da forma mais inteligente
                possível.
                </p>

                <%= link_to '',
                  class: 'btn btn-primary btn-lg top' do %>
                  Experimentar
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="properties">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="bold text-center">Inspire-se com a nossa seleção</h3>
        <p class="text-center">Confira as oportunidades que separamos para você.</p>
        <br />

        <div class="row">
          <% (1..12).each do |property| %>
            <div class="col-md-3 property">
              <div class="panel-heading"></div>
              <div class="panel panel-default">
                <div class="panel-body">
                  <h4 class="bold">Legi Perdizes</h4>
                  <p>Apresentamos o Monogram, um produto
                  imobiliario de alto padrão que une arquitetura
                  sofisticada, decor...
                  </p>

                  <ul class="list-unstyled list-inline" style="margin-top: 15px;">
                    <li>
                      <p>
                        <i class="fa-solid fa-ruler"></i>
                        121m²
                      </p>
                    </li>
                    <li>
                      <p>
                        <i class="fa-solid fa-building"></i>
                        Não iniciada
                      </p>
                    </li>
                    <li>
                      <p>
                        <i class="fa-solid fa-bed-pulse"></i>
                        3
                      </p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>

          <br />

          <div class="text-center">
            <%= link_to 'Veja mais destaques', properties_path, 
            class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="financial">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <h3 class="bold">Calculadora e simulador de<br />
                financiamento imobiliário
                </h3>

                <p>Use nossa calculadora para descobrir como
                aproveitar seu<br /> investimento da forma mais inteligente
                possível.
                </p>

                <%= link_to '',
                  class: 'btn btn-primary btn-lg top' do %>
                  Experimentar
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/landing_pages/franchise/index.html.erb
<section id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="bold">Faça parte da<br /> ImoSB</h1>
        <p>Venha fazer mais negócios e ampliar seus ganhos<br />
        unindo-se à rede de imobiliárias que mais vende<br />
        imóveis no Brasil.
        </p>
        
        <p>Abra uma franquia da ImoSB e torne-se membro da <br/>
        ImoSB
        </p>

        <%= link_to '', 
          class: 'btn btn-primary btn-lg top' do %>
          Quero saber mais
        <% end %>
      </div>
    </div>
  </div>
</section>

<section id="benefits">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="bold text-center">Explore todos os benefícos de se
        tornar<br /> um franqueado da ImoSb
        </h3>
        <br />

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h4 class="bold">Acesso ao mercado de<br /> lançamentos</h4>
              <p>Apoio para trabalhar e acessar os
              lançamentos do mercado primário
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="franchising">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="text-center">A <span class='bold'>Rede ImoSB</span> 
        pela visão<br /> de nossos franqueados.
        </h2>
        <br />
        
        <div class='row'>
          <% (1..3).each do |testimonial| %>
            <div class="col-md-4">
              <div class="well"></div>
              <h4 class="bold">Sobre a Força da Marka</h4>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">

        </div>

        <div class="col-md-2">
          <h4 class="bold">IMOSB</h4>
          <ul class="list-unstyled">
            <li><%= link_to 'Quem Somos', '' %></li>
            <li><%= link_to 'Fale Conosco', '' %></li>
            <li><%= link_to 'Assessoria de Imprensa', '' %></li>
            <li><%= link_to 'Termos e Condições', '' %></li>
            <li><%= link_to 'Trabalhe conosco', '' %></li>
            <li><%= link_to 'Seja um corretor associado', '' %></li>
            <li><%= link_to 'Relação com investidores', '' %></li>
            <li><%= link_to 'Conheça seu bairro', '' %></li>
            <li><%= link_to 'Construtoras e incorporadoras', '' %></li>
            <li><%= link_to 'Relatório de igualdade salarial', '' %></li>
          </ul>
        </div>

        <div class="col-md-2">
          <h4 class="bold">Serviços</h4>
          <ul class="list-unstyled">
            <li><%= link_to 'Venda seu imóvel', '' %></li>
            <li><%= link_to 'Alugue seu imóvel', '' %></li>
          </ul>
        </div>

        <div class="col-md-2">
          <h4 class="bold">Redes Sociais</h4>
          <ul class="list-unstyled">
            <li>
              <%= link_to '' do %>
                <i class="fa-brands fa-square-facebook"></i>
                Facebook
              <% end %>
            </li>
            <li>
              <%= link_to '' do %>
                <i class="fa-brands fa-twitter"></i>
                Twitter
              <% end %>
            </li>
            <li>
              <%= link_to '' do %>
                <i class="fa-brands fa-instagram"></i>
                Instagram
              <% end %>
            </li>
            <li>
              <%= link_to '' do %>
                <i class="fa-brands fa-linkedin-in"></i>  
                Linkedin
              <% end %>
            </li>
            <li>
              <%= link_to '' do %>
                <i class="fa-brands fa-youtube"></i>
                Youtube
              <% end %>
            </li>
            <li>
              <%= link_to '' do %>
                <i class="fa-solid fa-heart"></i>
                Blog
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <nav class="navbar navbar-default">
    <div class="container container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" 
        data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>
          Imosb
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Alugar', '' %></li>
          <li><%= link_to 'Comprar', '' %></li>
          <li><%= link_to 'Anunciar', '' %></li>
          <li><%= link_to 'Links úteis', '' %></li>
          <li><%= link_to 'Ajuda', '' %></li>
          <li><%= link_to 'Seja Franquedo', landing_pages_franchise_index_path %></li>
          <li><%= link_to 'Calculadora de Compra', '' %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Entrar', new_user_session_path %></li>
          <li><%= link_to 'Criar Conta', new_user_registration_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Imosb - <%= yield :title %></title>
    <meta charset="UTF-8" />
    <meta name="keywords" content="<%= yield :keywords %>" />
    <meta name="description" content="<%= yield :description %>" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
    <%= load_json_ld(yield :ld_json) %>
  </head>
  <body class="<%= controller.controller_name %>">
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>